### PR TITLE
Add a getFinite method to handle situations where the passed value is a non finite number (NaN, Infinity, etc.)

### PR DESCRIPTION
**Pull request by Kerruba**
I'm dealing with the situation where the value I want to check is read by _.toInteger from a String. This method return NaN, that is a Number (_.isNumber return true), but is not exactly what I'm looking for.
This new method should be able to handle these situation using as validator the _.isFinite instead

### CODE REVIEW

**Comment by Kerruba** [comment]
Actually the problem could be solved using _.toFinite(), but I think could be useful have a getFinite method too

**Comment by viveleroi** [comment]
I've been meaning to look into making these dynamic. Lodash has added dozens more `is***`-style methods and it seems like we can dynamically map `get***` variants. So if the argument to `getFinite` returns false for an `isFinite` check the default would be returned.

**Comment by viveleroi** [comment]
Well, since we have to hard-code default values I guess it can't be more dynamic than it is now.

**Comment by Kerruba** [comment]
I'm not sure what you mean with "more dynamic", if is let the user choose the checking function we should expose the `baseGetType` method letting the user pass a validation function. If instead with more dynamic you mean avoid the duplication of help method for each case, could we provide a way to "read" the default value type and use the corresponding type validator? 
I mean something like:
`getDefault(variable,"hello") \\ "hello" is a string, so the getDefault has to check if variable is a string`
`getDefault(variable,10) \\10 is an integer, so the getDefault check for an integer`
`getDefault(variable, false) \\false is a boolean, getDefault check for a boolean`

I'm not sure it makes sense, and more important is "safe"

**Comment by viveleroi** [comment]
I meant, I can generate `get____` variants for every `is___` method in lodash automatically, but if I do that I can't provide a default value - the user would always have to provide one. Not to mention that currently, auto-generated methods can't be documented properly.

**Comment by Kerruba** [comment]
I see, and in any case don't you think would be valuable to create such method and let the user provide the default? maybe is a method meant exactly for such purpose: user HAS to define a default value because he Want a specific value if nothing is returned.

**Comment by viveleroi** [comment]
Right, we can automate it if we force the user to the provide their own default, but that's less useful because at this stage it's really only saving them some ternary code. `_.getString(val, '')` versus `_.isString(val) ? val : '')`

**Comment by Kerruba** [comment]
Yeah but if we create a `_.valueOrDefault(val,'x')` where the user has just to type the default value and the method is unique and internally check which `_.is` is better to use based on the default value provided from the user would be nice and is a way more readable than a ternary operator...maybe... (personal opinion at least)

**Pull request closed without merging**
